config/routes.rb
Rails.application.routes.draw do
  post 'users/signin'

  get 'users/signout'

  get 'users/singin_get'

  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	self.per_page = 10
	has_paper_trail
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :user_signed_in?

  def current_user
  	unless @current_user
  		@current_user = User.where(session[:user_id]).first
	end
	@current_user
  end

  def user_signed_in?
  	!current_user.nil?
  end


  def authenticate_user!
  	return redirect_to users_singin_get_path unless user_signed_in?
  end




end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  helper_method :user_details
  before_action :authenticate_user!
  # GET /blogs
  # GET /blogs.json
  def index
    @search = params[:search]
    if @search && @search.length > 0
      @blogs = Blog.where("title like '%#{@search}%' or content like '%#{@search}%'").paginate(:page => params[:page]).order('created_at DESC')
    else
      @blogs = Blog.paginate(:page => params[:page]).order('created_at DESC')
    end

  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_details
    current_user.email
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :published)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signin
  	email = params[:email]
  	password = params[:password]
  	user =  User.find_by_email_and_password(email, password)
  	if user
  		session[:user_id] = user.id
  		return redirect_to '/blogs'
  	else
  		return redirect_to users_singin_get_path
  	end

  end

  def signout
  end

  def singin_get
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def prettify_boolean bool
		bool ? "Yes" : "No"
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<h2><%= user_details %></h2>
<h1>Listing Blogs</h1>

<%= current_user.email %>

<%= prettify_boolean user_signed_in? %>
<%= will_paginate @blogs %>


<%= form_tag '/blogs', method: :get do %>
<%= text_field_tag :search , @search %>


<%= submit_tag "Search" %>

<% end %>

<table id="blogs">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= prettify_boolean blog.published %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @blogs %>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>Published:</strong>
  <%= @blog.published %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/signin.html.erb
<h1>User#signin</h1>
<p>Find me in app/views/user/signin.html.erb</p>

app/views/users/signout.html.erb
<h1>User#signout</h1>
<p>Find me in app/views/user/signout.html.erb</p>

app/views/users/singin_get.html.erb
<h1>User#singin_get</h1>
<p>Find me in app/views/user/singin_get.html.erb</p>

<%= form_tag users_signin_path do %>
<%= label_tag :email %>
<%= text_field_tag :email %>
<br>

<%= label_tag :password %>
<%= password_field_tag :password %>
<br>
<%= submit_tag "Signin" %>

<% end %>